### ISSUE TITLE
answer arc instructions are garbage

### ISSUE THREAD

**Issue by Ignus3** [07th-mod/guide#17]
This is very frustrating, it says the answer arcs are done, but the instructions are for completely different files that are not part of the ZIP which you acquire by downloading the patch. Also, putting "change some of these instructions to include -chiru" or "change 1-4 in the instructions to 5-8" is bullshit documentation. Fix your documentation, seriously. Please. It's the only problem, but it makes this unusable.

**Comment by ItaloKnox** [comment]
The answer arcs were not officially released yet and the documentation was not updated for that reason. Also, try growing a brain. You got one to be rude, but none to be useful.

**Comment by ItaloKnox** [comment]
Here are the reworked instructions, just in case.

### How to install the patch manually (for Windows and Mac)

1. Installing the graphics:
    - **Umineko Question Arcs**: Extract ``Umineko-Graphics.zip.001`` (the first part only, it should extract the rest automatically) inside the game folder.
    - **Umineko Answer Arcs**: Extract ``UminekoChiru-Graphics.7z.001`` (the first part only, it should extract the rest automatically) inside the game folder.
2. Installing the voices:
    - **Umineko Question Arcs**: Extract ``Umineko-Voices.zip`` inside the game folder.
    - **Umineko Answer Arcs**: Extract ``UminekoChiru-Voices.zip`` inside the game folder.
3. Rename the file `0.utf` inside your Umineko folder to `0_old.utf`
4. Put the patched `0.utf` file inside the folder
5. Rename and add the game executable:
    - **Umineko Question Arcs**:
        - **Windows**: Rename the file `Umineko1to4.exe` to `Umineko1to4_old.exe`. Put the patched `Umineko1to4.exe` inside the folder.
        - **Mac**: Extract the file ``Umineko1to4.app.zip`` inside the game folder. Overwrite all files if asked.
    - **Umineko Answer Arcs**:
        - **Windows**: Rename the file `Umineko5to8.exe` to `Umineko5to8_old.exe`. Put the patched `Umineko5to8.exe` inside the folder.
        - **Mac**: Extract the file ``Umineko5to8.app.zip`` inside the game folder. Overwrite all files if asked.
6. Extract all updates (if available) in order of release (v1, v2, v3, ...) inside the game folder. Overwrite all files if asked.

**Comment by Ignus3** [comment]
If they're not released then I apologize, I was under the impression they were, as all subsections were marked finished as of November 26th of last year, I figured it was plenty of time for the final polish and install instructions to be completed.

also, the repo does not include:
UminekoChiru-Graphics.7z.001
UminekoChiru-Voices.zip
Umineko5to8.exe

Unless I did something entirely wrong by clicking on the link to the answer arcs patch and selecting "download as zip" on the "clone or download" button. 

I do appreciate the updated documentation though, it's a pet peeve of mine, worked at a company with shit documentation and had to relearn everything my predecessors had done before me on EVERY. SINGLE. PROGRAM. Frustrated the hell out of me.

**Comment by ItaloKnox** [comment]
...Because the changes have not been published yet. That's why the links are marked as "Soon" in the current snapshot. All the big binaries are usually in our resources repository.

Also, the patch is currently in closed testing. If you want to try it join the Discord channel where all the resources and updates are released (link is on the wiki front page). The install method is currently very messy and scattered between multiple files, but that will be fixed once we officially release the patch.

I understand your frustration with the documentation because I'm also picky about this. But if you think you can make it better, please elaborate on what's wrong and what could be changed. I'm basically taking care of the wiki alone and I'm not even a native speaker. So getting *helpful* input really helps.

**Comment by Ignus3** [comment]
I get it, sorry, thanks for understanding. It's easy to feel like you're yelling at a brick wall with this stuff. I'll take a look at the discord, and I am a native English speaker with good English skills so maybe I can help with English polish passes or something, or with  helping to organize the files.

Helpful suggestions:

Add some more transparency about exactly what you were just explaining to me to the readme files, as it stands they're a bit unclear that the patch is not ready. For example, google "umineko answer arc ps3 patch" and you'll get a link directly to the github repo, with all 6 sections marked as complete, and then a link to install instructions that seem to imply it's not actually complete. 

something like "Patch is currently in closed testing" or add a section to the roadmap called something simple like "Patch complete" and leave that unmarked until it's finished, to make it easy at a glance for enthusiastic people like myself to tell exactly what's going on and not get frustrated trying to install the repo as is (meaning incomplete and unreleased)

**Comment by ItaloKnox** [comment]
You're correct. Actually, we didn't plan to take it to closed testing at all, but it turned out to be a good idea. Because of that, this decision ended up not being talked outside of Discord, so we kinda forgot about that. I'll pass along the message to the team working on the patch so they can put up a PSA about this.
