### ISSUE TITLE
Black screen after auto-patch & can't reinstall game after!!

### ISSUE THREAD

**Issue by raoul1311** [07th-mod/guide#4]
I'm getting a black screen after the auto-patch is done. I can still hear sound and see the close message.

Also can't redownload the game anymore after that auto-patch. Steam says CONTENT FILE LOCKED for me_mi_aw_a1.png in the CGalt folder. So I installed it on my second SSD and it worked, but after using auto-patch again, I'm getting the same Steam error again when trying to redownload the game.
So I can't play Chapter 1 anymore thanks to the auto-patch :-/

**Comment by ItaloKnox** [comment]
Sorry but I don't really understand what your issue is. I can suppose the auto-patcher is the installer, is that right? If you can't make the game work using the installer, then manually install the patch. The guide will walk you through the steps.

**Comment by raoul1311** [comment]
I installed the auto-patch for Chapter 1. Now when I started the game, the game screen was just black and the only thing I was able to see was the "close" message when I tried to close the game.
So the game didn't work for me anymore and I tried to redownload it, but at the end of the download, Steam says something about CONTENT FILE LOCKED https://gyazo.com/ae7e584f0fd22dbfa7d9b2a0336bbeeb
The reason for this error is the auto-patcher and I don't know how to fix this now.

**Comment by ItaloKnox** [comment]
Are you trying to install the patch **while** the game is being downloaded? Or did you try to install the patch **before** it was downloaded?

**Comment by raoul1311** [comment]
I installed the patch after the game was already downloaded.

**Comment by raoul1311** [comment]
And the patch broke my game, as I said I'm just getting a black screen so wanted to redownload it, but now I'm getting that CONTENT error in Steam.

**Comment by ItaloKnox** [comment]
I'm sure there's nothing wrong with the installer and it is a problem on your end. I can't make sure what is happening with your computer, but we never an issue like yours so that makes me believe it's an isolated case and unrelated to the patch (or installer).

As I already suggested before, [try manually installing the patch](https://github.com/07th-mod/guide/wiki/Part-1---Voice-and-Graphics-Patch#manual-installation-windowslinuxmac). Since you can't reinstall it, I also suggest you to close Steam and delete the game folder. Running Steam afterwards should allow you to uninstall the game and download it again.

**Comment by raoul1311** [comment]
It was a problem with the installer. I downloaded Higurashi on my second SSD and used the installer again, but I was still getting just a black screen again, so I uninstalled the game again and tried to redownload it and now I'm getting that same CONTENT LOCKED error on both of my SSDs.

**Comment by raoul1311** [comment]
Hmm, I deleted the "Streaming Assets" folder in Higurashi and not it works again.
I will try the manual update right now and see if it works.

**Comment by ItaloKnox** [comment]
As I said, this is an issue with your computer and Steam. The patch works and your issue is unrelated to it.
Some computers can't run the installer properly since they don't have the necessary permissions, that's why we keep the manual installation available. When the installer fails, it leaves unfinished parts that can break your game, which seems to be the case.

Since deleting the StreamingAssets folder seems to work, don't forget to verify the game cache and let it download the missing files before installing the patch (even manually). The patch alone doesn't have all the files needed to run the game.

**Comment by raoul1311** [comment]
I installed the patch manually now and it works.

**Comment by ItaloKnox** [comment]
Good, just make sure you are not missing any sounds or music after deleting the StreamingAssets folder. I'm glad you got it to work, if you need more help, I'll reopen this issue. 👍
