### ISSUE TITLE
Order of patch installation matters with ADV mode

### ISSUE THREAD

**Issue by Ascoat** [07th-mod/guide#6]
I installed the latest patch on a fresh Steam download, but I installed the "Voice and Graphics patch" before the graphics pack, leading to the following anomaly:

![screenshot](https://user-images.githubusercontent.com/20040718/28860467-fd77809a-7719-11e7-87f9-d365d7a27864.jpg)

Reapplying the main patch fixed the issue.  Either the conflicting images should be removed from the graphics pack or the wiki should be updated to specify that the main patch needs to go last.

It also feels odd that the "Voice and Graphics patch" contains neither voice files nor the PS3 graphics.

**Comment by ItaloKnox** [comment]
Hey, thanks for reporting this. The manual installation part wasn't updated so I guess we goofed this time.
I just fixed the order so it should now be more clear. We didn't plan to have the new textbox included in the (scripts) patch, so thanks for letting us know!

Btw, we'll eventually remove the old textbox from the graphics patch. Since it requires some downtime (and worse, for all patches), we're holding this as much as possible until we have to change other files in the patch. 

Also about the "Voice and Graphics patch", it's just a terminology thing. When it says "voice and graphics", it means that the scripts there are meant for the full package, the way we want people to play our patch. This happened after we adopted the voices-only patch. Since the scripts are significantly different inside between versions, we want to make it as clear as possible what it covers or not. :)

Anyway, thanks again! 👍
