### ISSUE TITLE
Mac Issues w/ Tatarigoroshi

### ISSUE THREAD

**Issue by distoclex** [07th-mod/guide#9]
Hi,

I have a Mac and I tried to follow the instructions, but I got confused in the difference between extracting and merging the files, so I messed up my game...

I followed most of the instruction correctly, I think. My Streaming Assets folder looks like this:

![screen shot 2017-11-11 at 11 36 27 am](https://user-images.githubusercontent.com/22529803/32691914-affd0e10-c6d4-11e7-91e0-e5f1364fc512.png)

But now my game looks like this:

![screen shot 2017-11-11 at 11 37 54 am](https://user-images.githubusercontent.com/22529803/32691920-d117671c-c6d4-11e7-8f42-8888cab7e997.png)

However, this still happens when I try to quit:

![screen shot 2017-11-11 at 11 38 09 am](https://user-images.githubusercontent.com/22529803/32691922-dbebdd12-c6d4-11e7-9cf7-e89a31c0cfeb.png)

Yeah, I followed all the instructions except with CG. Since both the textbox files and the image files are both named CG, I was afraid replacing the textbox CG with the image CG would ruin the game. What should I do?

**Comment by ItaloKnox** [comment]
Hello,

Our team is scattered around the world so I guess none of us are native speakers, so things get a little wonky sometimes. Sorry about that, I'll see if I can improve the tutorial and make it more clear.

Now, about your issue, from what I could look in the screenshot you are doing pretty well. I suppose you did put the ``s**`` folders inside the ``voice`` folder I asked to create so your issue might be in the ``CG`` folder as you noted. In this case, you should first extract the graphics patch (``Tatarigoroshi-CG.zip``, if I recall correctly) and then the textboxes. Since both use the same folder, just dropping them in order in ``StreamingAssets`` should prompt you about overwriting files. Just give it a yes and you're done.

There's one thing you have done wrong, though. I can see the folder ``Managed`` inside your ``StreamingAssets`` folder. It should be one folder back, as you can see here: 
![firefox_2017-11-11_15-50-34](https://user-images.githubusercontent.com/4702556/32692024-14dbe8f6-c6f8-11e7-9406-6f43ad929616.png)

Just put it where it belongs, overwrite the file (``Assembly-CSharp.dll``) and the game should properly open now. Also, don't forget to delete everything inside the folder ``CompiledScriptsUpdate``. If you don't know where it is, looking at your first screenshot should take you to the right place. 👍 

Anyway, I'll be here in case you need help. I want to make sure you get the game to run fine, so update me on your issue as soon as you can. 😄

**Comment by distoclex** [comment]
Okay,

So I updated the Managed folder in resources.
I also updated the CG folder and added the textbox files to the CG folder with the 500+ images.
I deleted the dummy file in the CompiledScriptsUpdate.
However, the game actually closes now...

Here is what my screens look like:
![screen shot 2017-11-11 at 12 38 17 pm](https://user-images.githubusercontent.com/22529803/32692430-7bfd8366-c6dd-11e7-8527-69da5d8f4810.png)
![screen shot 2017-11-11 at 12 38 28 pm](https://user-images.githubusercontent.com/22529803/32692431-7c0eecbe-c6dd-11e7-9312-f83d37e5e4a9.png)
![screen shot 2017-11-11 at 12 38 39 pm](https://user-images.githubusercontent.com/22529803/32692432-7c1e641e-c6dd-11e7-8149-573d508ae17c.png)
![screen shot 2017-11-11 at 12 39 30 pm](https://user-images.githubusercontent.com/22529803/32692433-7c2d0d48-c6dd-11e7-9ff6-8d9de37be998.png)
![screen shot 2017-11-11 at 12 39 48 pm](https://user-images.githubusercontent.com/22529803/32692434-7c4221a6-c6dd-11e7-97a6-7537679e4195.png)

Any thoughts?

**Comment by ItaloKnox** [comment]
Can you check if you downloaded the version [v4.0.1](https://github.com/07th-mod/tatarigoroshi/releases/tag/v4.0.1)?

We corrected this bug in this version so if it's not working for you it's very important to fix it right now.

**Comment by distoclex** [comment]
I downloaded v4.0.1

However, I may have just done the installation incorrectly. My game won't
open unless I reinstall and re-install with no configuration.

Sincerely,
distoclex

**Comment by distoclex** [comment]
*uninstall and re-install

**Comment by distoclex** [comment]
Actually, uninstalling and reinstalling does not work anymore.

**Comment by ItaloKnox** [comment]
Something weird is going on, if you are comfortable using the terminal can you mind using this update I just pushed to the tutorial? https://github.com/07th-mod/guide/wiki/Part-1---Voice-and-Graphics-Patch#how-to-use-the-installer-script-for-linux-and-mac

In case you can't we can try something else. Let me page my pals @enumag and @P-Chang to see if they have any suggestions.

Also, next time you post try looking for a file called ``output_log`` inside your game folder. Use the search to find it, not sure if Mac stores it in the same place as Windows, since the structure is a bit different for both versions of the game. If you find it, don't post the contents here, just attach the file to your comment.

**Comment by enumag** [comment]
@distoclex Vanilla game worked fine for you I assume? There is probably not much we can do about it without the log file.

**Comment by P-Chang** [comment]
I have not any report for DLL from Mac user before you create this issue.
So, I didn't check compatibility with Mac. Sorry for that.

Newest version have DLL that edited in my Win7 system.
Windows and Mac and Linux use almost same dll in vanilla but there are possibility that I broke compatibility for Mac.

I ask you new different question, I'm sorry if you will be confuse.

1.Please, clean install vanilla game and launch with vanilla
2.Download this http://www.mediafire.com/file/ycv6ae2ofp75a77/chapter3_mac_check.zip
3.Unzip and put Assembly-CSharp.dll to `\Contents\Resources\Data\Managed` and launch(It doesn't need any other mod files)

Patched DLL with vanilla have some problem but there are no problem with launch in Windows.

If you can't launch with patched dll, I broke compatibility.

**Comment by P-Chang** [comment]
I remember that output.log are not stored in game folder in chapter3 and 4. and I searched unity reference.

macOS | ~/Library/Logs/Unity/Player.log
-- | --
Windows XP | C:\Documents and Settings\username\Local Settings\Application Data\CompanyName\ProductName\output_log.txt
Windows Vista/7 | C:\Users\username\AppData\Local\CompanyName\ProductName\output_log.txt
Linux | ~/.config/unity3d/CompanyName/ProductName/Player.log

log file that we call like output.log are probably player.log in Mac

**Comment by enumag** [comment]
Closing as outdated. Feel free to open new issue if you have any problems.
